//
//  DecoderTests.swift
//  image-io-framework
//
//  Created by Fang Ling on 2026/2/13.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//

import Foundation
import FoundationFramework
@testable import ImageIOFramework
import Testing

@Suite("DecoderTests")
struct DecoderTests {
  @Test
  func testDecodeMetadata() {
    let blankJXLImageData = Data(
      base64Encoded: base64EncodedBlankJXLImageData
        .components(separatedBy: .newlines)
        .joined()
    )!
    let data = blankJXLImageData.withUnsafeBytes { buffer in
      Data(
        bytes: buffer.baseAddress!.assumingMemoryBound(
          to: UnsignedInteger8.self
        ),
        count: UnsignedInteger64(buffer.count)
      )
    }

    let imageSource = ImageSource(data: data)!
    let imageProperty = imageSource.imageProperty
    #expect(imageProperty?.width == 3024)
    #expect(imageProperty?.height == 4032)
  }
}

extension DecoderTests {
  var base64EncodedBlankJXLImageData: String {
    """
    AAAADEpYTCANCocKAAAAFGZ0eXBqeGwgAAAAAGp4bCAAAAAZanhscAAAAAD/Cvp96HmBBZV7qygC
    AAAATmJyb2JFeGlmG1MAAAT+bff+Nugu6C6BIPIRRJToCAPMDU4sQA80S/LSTYaNMfBUqyepM9nv
    hmniu0JwDxHBMh9eMlCW/suZ8QAAAAAA/WJyb2J4bWwgGx0CAORyTh+j/jJdAHRD1ckC0MVN1xbg
    Jt2L/uI1QcbkKPBEE02p54YjEJRi4HlAi3NzoF/q1U8vNMZ/RYXLwPmqqcSLgMKg9nlrDRw9P+CN
    Sw4iSZM0NhEA6EtWqD8/dFEtWWHgI56P6NItQ4dmKZYl6hux3sMWX8SwPhzJZbwIOvCEWcQGxnpi
    I3Z2y68aYVjJgQuh4KWPFEPSlCmZrS54EOFkoq47/Lv6qa+8+/t1nw9rPQ4mT3OsTomXzRERh6NZ
    nmBUeGM3LkkcmYzZmD224Ec/VN9LnQ/bRuJpni/RlU6ttRhIi8LERDqVFb6JAAAACWVqeGxwgAAA
    AQgIEIABYsB7HWOsSsXgS83uaKyuAwhBQFCGFRCTvUF0lwqUnHHyFfDdCwCYEWf9QKR3CgrfEO4H
    AN4AANAHACAAAiAAAiAAAiAAAiAAAiAAAiAAAiAAAiAAAiAAAiAAAiAAAiAAAiAAAiAAAiAAAiAA
    AiAAAiAAAiAAAiAAAiAAAiAAAiAAAiAAAiAAAiAAAiAAAiAAAiAAAiAAAiAAAgAAAiAAAiAAAiAA
    AiAAAiAAAiAAAiAAAiAAAiAAAiAAAiAAAiAAAiAAAiAAAiAAAiAAACAAAiAAAiAAAiAAAiAAAiAA
    AiAAAiAAAiAAAiAAAiAAAiAAAiAAAiAAAiAAAiAAAiAAAiAAAiAAAiAAAiAAAiAAAiAAAiAAAiAA
    AiAAAiAAAiAAAiAAAiAAAiAAAiAAAgAAAiAAAiAAAiAAAiAAAiAAAiAAAiAAAiAAAiAAAiAAAiAA
    AiAAAiAAAiAAAiAAAiAAAIkkUSxYSAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAABkCSKBYsJAEGQJIoFiwkAQZAkigWLCQBBkCSKBYsJAEGQJIoFiwkAQZAkigWLCQBBkCSKBYs
    JAEGQJIoFiwkAQZAkigWLCQBBkCSKBYsJAEGQJIoFiwkAQZAkigWLCQBBkCSKBYsJAEGQJIoFiwk
    AQZAkigWLCQBBkCSKBYsJAEGQJIoFiwkAQZAkigWLCQBBkCSKBYsJAEGQJIoFiwkAQZAkigWLCQB
    BkCSKBYsJAEGQJIoFiwkAQZAkigWLCQBBkCSKBYsJAEGQJIoFiwkAQZAkigWLCQBBkCSKBYsJAEG
    QJIoFiwkAQZAkigWLCQBBkCSKBYsJAEGQJIoFiwkAQZAkigWLCQBBkCSKBYsJAEGQJIoFiwkAQZA
    kigWLCQBBkCSKBYsJAEGQJIoFiwkAQZAkigWLCQBBkCSKBYsJAEGQJIoFiwkAQZAkigWLCQBBkCS
    KBYsJAEGQJIoFiwkAQZAkigWLCQBBkCSKBYsJAEGQJIoFiwkAQZAkigWLCQBBkCSKBYsJAEGQJIo
    FiwkAQZAkigWLCQBBkCSKBYsJAEGQJIoFiwkAQZAkigWLCQBBkCSKBYsJAEGQJIoFiwkAQZAkigW
    LCQBBkCSKBYsJAEGQJIoFiwkAQZAkigWLCQBBkCSKBYsJAEGQJIoFiwkAQZAkigWLCQBBkCSKBYs
    JAEGQJIoFiwkAQZAkigWLCQBBkCSKBYsJAEGQJIoFiwkAQZAkigWLCQBBkCSKBYsJAEGQJIoFiwk
    AQZAkigWLCQBBkCSKBYsJAEGQJIoFiwkAQZAkigWLCQBBkCSKBYsJAEGQJIoFiwkAQZAkigWLCQB
    BkCSKBYsJAEGQJIoFiwkAQZAkigWLCQBBkCSKBYsJAEGQJIoFiwkAQZAkigWLCQBBkCSKBYsJAEG
    QJIoFiwkAQZAkigWLCQBBkCSKBYsJAEGQJIoFiwkAQZAkigWLCQBBkCSKBYsJAEGQJIoFiwkAQZA
    kigWLCQBBkCSKBYsJAEGQJIoFiwkAQZAkigWLCQBBkCSKBYsJAEGQJIoFiwkAQZAkigWLCQBBkCS
    KBYsJAEGQJIoFiwkAQZAkigWLCQBBkCSKBYsJAEGQJIoFiwkAQZAkigWLCQBBkCSKBYsJAEGQJIo
    FiwkAQZAkigWLCQBBkCSKBYsJAEGQJIoFiwkAQZAkigWLCQBBkCSKBYsJAEGQJIoFiwkAQZAkigW
    LCQBBkCSKBYsJAEGQJIoFiwkAQZAkigWLCQBBkCSKBYsJAEGQJIoFiwkAQZAkigWLCQBBkCSKBYs
    JAEGQJIoFiwkAQZAkigWLCQBBkCSKBYsJAEGQJIoFiwkAQZAkigWLCQBBkCSKBYsJAEGQJIoFiwk
    AQZAkigWLCQBBkCSKBYsJAEGQJIoFiwkAQZAkigWLCQBBkCSKBYsJAEGQJIoFiwkAQZAkigWLCQB
    BkCSKBYsJAEGQJIoFiwkAQZAkigWLCQBBkCSKBYsJAEGQJIoFiwkAQZAkigWLCQBBkCSKBYsJAEG
    QJIoFiwkAQZAkigWLCQBBkCSKBYsJAEGQJIoFiwkAQZAkigWLCQBBkCSKBYsJAEGQJIoFiwkAQZA
    kigWLCQBBkCSKBYsJAEGQJIoFiwkAQZAkigWLCQBBkCSKBYsJAEGQJIoFiwkAQZAkigWLCQBBkCS
    KBYsJAEGQJIoFiwkAQZAkigWLCQBBkCSKBYsJAEGQJIoFiwkAQZAkigWLCQBBkCSKBYsJAEGQJIo
    FiwkAQZAkigWLCQBBkCSKBYsJAEGQJIoFiwkAQZAkigWLCQBBkCSKBYsJAEGQJIoFiwkAQZAkigW
    LCQBBkCSKBYsJAEGQJIoFiwkAQZAkigWLCQBBkCSKBYsJAEGQJIoFiwkAQZAkigWLCQBBkCSKBYs
    JAEGQJIoFiwkAQZAkigWLCQBBkCSKBYsJAEGQJIoFiwkAQZAkigWLCQBBkCSKBYsJAEGQJIoFiwk
    AQZAkigWLCQBBkCSKBYsJAEGQJIoFiwkAQZAkigWLCQBBkCSKBYsJAEGQJIoFiwkAQZAkigWLCQB
    """
  }
}
